### ISSUE TITLE
Python 3.11 as dependency

### ISSUE THREAD

**Issue by endreszabo** [VoxelCubes/DeepQt#1]
How strict is the requirement for Python 3.11? Python 3.11 was not even released (oct 2022) when this commit was made (sep 2022):

https://github.com/VoxelCubes/DeepQt/blob/e05799b7da31cb7443eb8f564568068f68165445/setup.cfg#L31

My PIP with Python 3.10 brags about not having 3.11 installed.

`deepqt 1.1.0 requires python_version>"3.10", which is not installed.`

**Comment by VoxelCubes** [comment]
Oh, that's odd, because I don't have Python 3.11 myself. It should work just fine with Python 3.10, not below, however. I'll fix that, thanks!
